// tsc -p .\tsconfig.json => src => lib
/**
 * The rollup file is additional it produces
 * ./dist with the already known builds
 * as typescript got deprecated
 * this now directly ships lib and only
 * has the tssrc as reference to optimize
 * type output. in later Iterations.
 */
import terser from '@rollup/plugin-terser';
import { defineConfig } from 'rollup';

import pkg from './package.json' with { type: 'json' };

const version = (process && process?.env?.SEMANTIC_RELEASE_NEXT_VERSION) || pkg.version;

console.log('building version:', version);

const banner = `/**
 * marked v${version} - a markdown parser
 * Copyright (c) 2011-${new Date().getFullYear()}, 
 * Christopher Jeffrey. (MIT Licensed)
 * https://github.com/markedjs/marked
 */

/**
 * DO NOT EDIT THIS FILE
 * The code in this file is generated from files in ../lib/
 */
`;

export default defineConfig([
  {
    input: 'lib/marked.js',
    output: [
      { file: 'packages/marked/dist/marked.esm.js', format: 'esm', sourcemap: true, banner },
      { file: 'packages/marked/dist/marked.umd.js', format: 'umd', name: 'marked', sourcemap: true, banner },
      {
        file: 'packages/marked/dist/marked.min.js',
        format: 'umd',
        name: 'marked',
        sourcemap: false,
        banner,
        plugins: [
          terser({
            format: {
              comments: (node, comment) => {
                if (comment.type === 'comment2') {
                  return comment.value.includes('Copyright (c)');
                }
              },
            },
          }),
        ],
      },
      { file: 'packages/marked/dist/marked.cjs', format: 'cjs', name: 'marked', sourcemap: true, banner },
    ],
  },
]);
